### PR TITLE
Ukrainian localization

### PR DESCRIPTION
**Pull request by stenox**

### CODE REVIEW

**Comment by cooperq** [comment]
I am ready to merge this pull request! I just need to make sure you agree to the new license (it has changed since you opened your pull request) https://github.com/EFForg/privacybadgerfirefox/blob/master/LICENSE

**Comment by stenox** [comment]
Yes. I acknowledge and agree to the new license.

**Comment by cooperq** [comment]
Thank you! this is fantastic!  Would you be interested in localizing the chrome version as well?

**Comment by stenox** [comment]
At the moment not. I have whole Mozilla localization, several add-ons and also some other applications.
And I don't use google chrome )
Thanks and waiting for the next update with Ukrainian localization :)

**Pull request merged**
