### PR TITLE
refactor cookieblocking, fixes #206

### LINKED ISSUE #206: Request: do not allow exeption automatically in Firefox' s cookie accepted list
Hi, 
I notice thatPrivacyBager adds websites in the Firefox's cookies whitelist, for example from www.paypal.com and wikimedia.org, withouth any advice, and these exeptions remain for each session of Firefox, even if I use the Private browsing mode.
I want that these exeption were removed when you close Firefox.

### PR DESCRIPTION
**Pull request by cooperq**
cc @SwartzCr or @pde for approval. 
This gets privacy badger to stop relying on firefox's cookie permissions for cookie blocking (which causes a whole host of side effects, see the list in #206) and uses our own logic for cookie blocking instead. Stripping headers and clobbering js cookies. 
I can't really tell you an easy way to test this, cookie block something, delete all of it's cookies, and make sure it can't set new cookies, I guess. All the tests pass, so there is that. 

Fixes #206

### CODE REVIEW

**Comment by SwartzCr** [comment]
There seem to be major problems with the pop-up
steps to reproduce:
go to cnn.com
yellowlist a domain
refresh the page, watch as the badge number doesn't not increase monotonically
notice things like this happening where something is yellowlisted according to the settings, but isn't showing up yellowlisted on the pop-up for that page
cookiestorage

**Comment by cooperq** [comment]
Yep, I can reproduce those bugs as well, but I have no idea what you mean by this:
> refresh the page, watch as the badge number doesn't not increase monotonically
I will fix this.

**Comment by cooperq** [comment]
Okay I have fixed all the bugs! This should work like a charm now, thanks Noah!

**Comment by SwartzCr** [comment]
okay, so for the most part this works, BUT I've noticed two issues:
1) and I can't seem to repro it, but set a domain to yellow or red for the top level, then go to the site and see all of the subdomains yellow listed, then manually set one of them to userGreen. When I reverted control over it, it stayed green for some reason. My guess is that this stems from a problem with getOriginalAction in contentPolicy, which goes to canAccessCookies which checks prefs from network.cookie.cookieBehavior, which checks in FF settings what that domain is meant to do, but doesn't check if the parent domain is on a list. Confusing, I know, so maybe getOriginalAction should change its logic to just not check that and instead do a check of lists for parent and then the FF equivalent of heuristic like in chrome
2) This one is up to you to debug, but go to a site like CNN (why do I always go to CNN) and then go to settings and yellowlist something like outbrain. Then go back to CNN and user green some of the outbrain domains. For me they stop appearing in the pop-up at all. When I had problem 1, they were able to set cookies and I saw cookies come up in the FF cookie list, here they aren't
My guess is this has to do with the fallback in canAccessCookies where it checks if there are cookies in the DB, and it's defaulting to blocking the cookies. Why they're not showing up in the popup I don't really know. Something tells me it's like bugging out somewhere?
Feel free to call me with questions

**Comment by cooperq** [comment]
1) I also can't repro this, I will look at getOriginalAction, but I also don't think this bug is likely to come up again after you have your eTLD changes landed. 
2) I am also not able to repro this, could it have to do with things getting blocked by abp? Here is a screenshot where I tried to follow your exact steps. .
screenshot from 2015-07-22 11 29 19

**Comment by SwartzCr** [comment]
Try it again, but set outbrain to red in options
I don't have ABP installed

**Comment by cooperq** [comment]
I get a different bug where if outbrain.com is set to red all of its subdomains look to be cookie blocked, I think this is probably related to the bug that you discovered yesterday.

**Comment by SwartzCr** [comment]
YES! BUT
then watch what happens when you mess with other settings
SPECIFICALLY things stay yellowlisted
outbrain

**Comment by cooperq** [comment]
Okay yea that one I can reproduce, I will look into it a bit, but I wonder if it will go away with your ETLD fixes. Either way I think I should fix the logic that we were looking at yesterday and see if that fixes this problem.

**Comment by SwartzCr** [comment]
yeah, start here, but I think there's another level that matters:
@@ -396,7 +396,14 @@ var Policy = exports.Policy = {
         return (parentHost in storage.userRed);
       }, true /*ignoreSelf*/);
     }
-    if (_isParentYellow() || _isParentRed()) {
+    if (_isParentRed()){
+      if (window) {
+        emit(settingsMap, "update-settings", "block", window, host);
+      }
+      cookieUtils.clobberCookie(host);
+      return true;
+    }
+    if (_isParentYellow() ) {
       if (window) {
         emit(settingsMap, "update-settings", "cookieblock", window, host);
       }

**Comment by cooperq** [comment]
Okay, I think I have fixed all of the above noted bugs now. Let me know if you find more.

**Comment by SwartzCr** [comment]
issue 1:
12321321.log.optimizely.com isn't blocked when optimizely.com is blocked
outbrain2
issue 2:
yellowlist a tld, green list it's subdomains, revert control of those sub domains, see that they don't return to yellowlist
outbrain4

**Comment by cooperq** [comment]
I couldn't reproduce issue 2 but maybe this fixes it anyway? Issue 1 is fixed now for sure.

**Comment by SwartzCr** [comment]
Issue 1: subdomain rules get overriden by TLD rules
outbrain-no-override


Issue 2: test parseCookieString on line 87 of test-utils.js is failing because it's getting an object {} instead of a string ""

**Comment by cooperq** [comment]
1. yes they do if that top level domain is red. Isn't this problem going to go away with your ETLD changes anyway, since users cant change subdomains if they have changed the top level domain?
2. weird, didn't even notice that, I will fix the test.

**Comment by SwartzCr** [comment]
no, because if I set it before I set the TLD rule then they get overruled. It works the other way in chrome, where you can have specific rules and everything else gets dealt with by the top level rule.
The logic is something like
"is this a user set rule?"
"what color is it"
"is this domain in that color's store"
if not "is this domain's parent there"
if so lump it in with the rest ruled by the parent

**Comment by SwartzCr** [comment]
(wanna do standup?)

**Comment by cooperq** [comment]
pushed a commit that fixes the test.

**Comment by cooperq** [comment]
all fixed now, I think we should write up your battery of tests as unit tests though!

**Comment by SwartzCr** [comment]
I am now getting an issue where things aren't reverting from yellow list :(
It looks to be happening every time
to reproduce yellow list a tld, refesh the site, see them all yellow listed (with no user revert option), revert on the options page, refresh the other page and see that they're all still yellow listed, and stuck there in perpetuity

**Comment by cooperq** [comment]
Okay, this fixes the latest bug (and even adds some tests for once!) Hopefully this is the last bug.

**Comment by SwartzCr** [comment]
looks good
only small issue is that things that get yellowlisted for TLD don't get a revert icon on the pop-up
I'm going to merge, and then work on fixing that in the eTLD fix

**Comment by cooperq** [comment]
WOOHOO!!! :tada: :tada: :tada:

**Pull request merged**
