### PR TITLE
Whitelist private hosts

### PR DESCRIPTION
**Pull request by rcutmore**
This is in reference to issues #596 and #682. Let me know if there are any problems with this or any changes you'd like to see.

### CODE REVIEW

**Comment by cooperq** [comment]
Wow, this is excellent work! It's even commented and tested! Thank you for the patch. :+1: 

The only thing that I would note is that the IP space for localhost is actually 127.0.0.0/8, which we might wish to account for. But I think that can be done separately.

**Comment by cooperq** [comment]
Is there any chance you would be interested in porting this code over to the chrome version as well?

**Comment by rcutmore** [comment]
Sure thing, I should be able to take a look at the Chrome version within the next week or two.

**Comment by cooperq** [comment]
Thanks this looks excellent! Sorry for the delay in merging!

**Pull request merged**
