### PR TITLE
Create ru.properties

### PR DESCRIPTION
**Pull request by stenox**
Russian localization by Aleksandr Gladkov from https://www.transifex.com/privacy-badger-for-firefox/privacy-badger-for-firefox/language/ru/

### CODE REVIEW

**Comment by cooperq** [comment]
Ah, someone else just submitted a russian translation as well, can you look at it and see if there are any changes that should be merged in from this one?

**Comment by stenox** [comment]
Yes, now I see.
In order to avoid such conflicts, didn't you think about centralized resources for localization like Transifex?
By the way, I've created Privacy Badger localization project there: https://www.transifex.com/privacy-badger-for-firefox/

**Comment by cooperq** [comment]
I thought that transifex cost money, is that not the case? Either way - I will soon be merging the two privacy badgers into a single code base. Once that is complete, I am happy to figure out how to use transifex and get privacy badger on there if that makes it easier for people to translate!

**Comment by RiseT** [comment]
From Transifex' [pricing page](https://www.transifex.com/pricing/):

*[...] we continue to maintain an “Open Source” program with the intent of supporting organizations that have no funding, revenue, and/or commercialization model. Our OS program also supports our technology partners with distributed teams and limited localization resources. To understand whether you qualify for our Open Source program, please contact us.*

**Pull request closed without merging**
