### PR TITLE
Issue 516

### PR DESCRIPTION
**Pull request by cooperq**
fix cookie checking in response headers when user has turned off all cookies in firefox. 

CC @SwartzCr for review.

### CODE REVIEW

**Comment by cooperq** [comment]
How to test:
Before: Run clean firefox with cookies disabled. See that  nothing gets marked as tracking. 
After: Run clean firefox with cookies disabled. See that privacy badger still detects trackers as expected.

**Comment by SwartzCr** [comment]
Two things:
When testing I noticed that kinja.com got yellowlisted immediately on buzzfeed, which is strange since that's the only site that it should be loaded on.
Also do you think this would be a good opportunity for an added test to check that trackers get noticed when cookies are disabled in the browser?

**Comment by cooperq** [comment]
as to your first point I was able to reproduce it but it also exists on master, so I think it should be marked as a seperate issue. 
for the second point, yea I could probably write a test for this but I would rather do that after I get a bugfix release out, since I don't think it's going to be particularly easy to test.

**Comment by SwartzCr** [comment]
okay, i'm in favor of merging as long as a bug is opened for the yellowlisting non-cross domain trackers

**Pull request merged**
