### PR TITLE
Fixes text alignment of notracking

### PR DESCRIPTION
**Pull request by frankcash**
Adds text-align:left so when text overflows starts on right side

This is all in reference to issue #530 

privacy-badger-issue-530

### CODE REVIEW

**Comment by cooperq** [comment]
Thank you for your contribution! I think that maybe a better solution though is to make the text smaller, and do it in the css file instead of the html file. If you can make those changes I would be happy to merge your pull request.

**Comment by frankcash** [comment]
@cooperq do you want me to just make the text reading `The following domains don't appear to be tracking you` smaller or all of the text?

**Comment by cooperq** [comment]
Just `the following domains...` please!

**Comment by frankcash** [comment]
Okay, I updated the pull to include this.  Here is the updated screenshot.

screen shot

**Comment by cooperq** [comment]
Very nice! Thanks!

**Pull request merged**
